import {
  Bot, Sparkles, Brain, Globe, Cpu, Cloud, Layers, Network, Atom, Star,
  Zap, Rocket, BarChart, Search, Database, Monitor, CloudLightning, Smartphone,
  FileText, Heart, BookOpen, Lightbulb, GitBranch, Shield, Eye, Terminal,
  Music, Radio, Server, Box, Cog, CloudSun, CloudRain, CloudMoon, Code, Workflow,
  Ghost, WandSparkles, Flame, TreePine, Compass, Paintbrush, Video, Flower2, Bug,
  Moon, Puzzle, Ship, Gem, type LucideIcon,
} from 'lucide-react';

/**
 * ICON MAPPING
 *
 * Map each model creator (slug) and provider (name) to a lucide-react icon.
 * Unmapped entries fall back to `Bot`.
 *
 * To add an icon: find the slug/name in the object and set it to any lucide icon.
 * Example: creatorIcons['OpenAI'] = Sparkles;
 */

export const defaultIcon: LucideIcon = Bot;

export const creatorIcons: Record<string, LucideIcon> = {
  'OpenAI': Sparkles,
  'Anthropic': Brain,
  'Google': Globe,
  'DeepSeek': Cpu,
  'Meta': Layers,
  'Mistral': Cloud,
  'Alibaba Qwen': CloudSun,
  'Cohere': Network,
  'xAI': Atom,
  'MoonshotAI': Rocket,
  'Z.ai': Zap,
  'NVIDIA': Cpu,
  'MiniMax': BarChart,
  'Amazon': CloudRain,
  'Microsoft': Monitor,
  'Perplexity': Search,
  'IBM': Database,
  'ByteDance': CloudLightning,
  'ByteDance Seed': CloudLightning,
  'Tencent': Globe,
  'Xiaomi': Smartphone,
  'StepFun': Star,
  'Kwaipilot': Rocket,
  'Nex AGI': Brain,
  'Sakana AI': Workflow,
  'Nous Research': Code,
  'Writer': FileText,
  'Upstage': Rocket,
  'Inflection': Heart,
  'AI21 Labs': BookOpen,
  'Inception': Lightbulb,
  'Morph': GitBranch,
  'Arcee AI': Shield,
  'Reka': Eye,
  'Relace': Terminal,
  'Perceptron': Cpu,
  'Baidu': CloudSun,
  'Allen AI': Atom,
  'Deep Cogito': Brain,
  'TheDrummer': Music,
  'Sao10K': Star,
  'Poolside': Code,
  'inclusionAI': Workflow,
  'AionLabs': Sparkles,
  'OpenRouter': Radio,
  'Gryphe': Ghost,
  'Mancer': WandSparkles,
  'Undi95': Star,
  'Anthracite': Flame,
  'Cognitive Computations': Brain,
};

export const providerIcons: Record<string, LucideIcon> = {
  'OpenAI': Sparkles,
  'Anthropic': Brain,
  'Azure': CloudRain,
  'Amazon Bedrock': CloudRain,
  'Amazon': CloudRain,
  'Amazon Nova': CloudRain,
  'Google': Globe,
  'Google AI Studio': Globe,
  'DeepSeek': Cpu,
  'DeepInfra': Server,
  'Fireworks': Zap,
  'Together': Network,
  'Groq': Zap,
  'Novita': Cloud,
  'Featherless': Box,
  'Recursal': Cog,
  'Hyperbolic': Atom,
  'Lepton': Radio,
  'Infermatic': Cloud,
  'Lambda': Server,
  'Nineteen': Cloud,
  'Chutes': Cloud,
  'Kluster': Server,
  'Reflection': Eye,
  'Liquid': Cloud,
  'Alibaba': CloudSun,
  'Baidu': CloudSun,
  'SiliconFlow': Cpu,
  'DigitalOcean': CloudLightning,
  'Venice': CloudMoon,
  'Morph': GitBranch,
  'Parasail': Rocket,
  'WandB': BarChart,
  'AkashML': Cloud,
  'AtlasCloud': Globe,
  'Io Net': Radio,
  'StreamLake': Cloud,
  'GMICloud': Cloud,
  'AI21': BookOpen,
  'AionLabs': Sparkles,
  'Ambient': Cloud,
  'Avian': Cloud,
  'BaseTen': Server,
  'Black Forest Labs': TreePine,
  'Cerebras': Cpu,
  'Cirrascale': Server,
  'Clarifai': Eye,
  'Cloudflare': Cloud,
  'Crucible': Gem,
  'Crusoe': Zap,
  'Darkbloom': Flower2,
  'Decart': Box,
  'Deepgram': Radio,
  'DekaLLM': Cpu,
  'FakeProvider': Bug,
  'Friendli': Heart,
  'HeyGen': Video,
  'Inception': Lightbulb,
  'Inceptron': Cpu,
  'Inferact vLLM': Zap,
  'InferenceNet': Network,
  'Inflection': Heart,
  'Ionstream': Zap,
  'Mancer 2': WandSparkles,
  'Mara': Cloud,
  'Meta': Layers,
  'Minimax': BarChart,
  'Mistral': Cloud,
  'ModelRun': Rocket,
  'Modular': Puzzle,
  'Moonshot AI': Rocket,
  'NCompass': Compass,
  'Nebius': Cloud,
  'Nex AGI': Brain,
  'NextBit': Cpu,
  'Nvidia': Cpu,
  'OpenInference': Search,
  'OpenRouter': Radio,
  'Perceptron': Cpu,
  'Perplexity': Search,
  'Phala': Shield,
  'Poolside': Code,
  'Quiver': Zap,
  'Recraft': Paintbrush,
  'Reka': Eye,
  'Relace': Terminal,
  'Sail Research': Ship,
  'Sakana AI': Workflow,
  'SambaNova': Zap,
  'Seed': Flower2,
  'Sourceful': Heart,
  'Stealth': Moon,
  'StepFun': Star,
  'Switchpoint': Zap,
  'Tencent': Globe,
  'Tenstorrent': Zap,
  'Upstage': Rocket,
  'Wafer': Cpu,
  'xAI': Atom,
  'Xiaomi': Smartphone,
  'Z.AI': Zap,
};

export function getCreatorIcon(creator: string): LucideIcon {
  return creatorIcons[creator] || defaultIcon;
}

export function getProviderIcon(provider: string): LucideIcon {
  return providerIcons[provider] || defaultIcon;
}